### PR TITLE
chore: update features versions

### PR DESCRIPTION
**Pull request by johnny243**
Asana tasks:

- https://app.asana.com/0/1199914526147392/1201333341451194
- https://app.asana.com/0/1199914526147392/1201330615340292

### CODE REVIEW

**Review by mobitar — APPROVED** [review]
You'll need to increment features version in package.json, packages/snjs/package.json, and auth/package.json.

**Comment by johnny243** [comment]
> You'll need to increment features version in package.json, packages/snjs/package.json, and auth/package.json.

Why `auth/package.json`?

**Comment by mobitar** [comment]
Auth is who serves the features to users.

**Comment by mobitar** [comment]
Auth is who serves the features to users.

**Pull request merged**
