### PR TITLE
fix: custom filtering for notes when a tag is set

### PR DESCRIPTION
**Pull request by baptiste-grob**

### CODE REVIEW

**Comment by baptiste-grob** [comment]
(I think I've figured out a better way to do this, removing request for review)

**Comment by baptiste-grob** [comment]
The solution ends up being much more involved and I don't want to delay this fix. Will post a subsequent PR if it bears fruit

**Comment by mobitar** [comment]
Can you elaborate on the ideal solution, for posterity?

**Comment by baptiste-grob** [comment]
The ideal solution would be for `ItemCollectionNotesView` to construct a custom filter function that can handle tags in the most efficient manner possible, and pass it to `ItemCollection.setDisplayOptions(...)`.
Right now by filtering items after the fact, `ItemCollection` is wasting time sorting items that are bound to be removed later.

**Pull request merged**
